num_agent: 4
car1:
    name: "car1"
    color: "0000FF" #blue
car2:
    name: "car2"
    color: "00FF00" #green
car3:
    name: "car3"
    color: "FF0000" #red
car4:
    name: "car4"
    color: "800080" #purple
car5:
    name: "car5"
    color: "800080" #purple
car6:
    name: "car6"
    color: "800080" #purple
car7:
    name: "car7"
    color: "800080" #purple
car8:
    name: "car8"
    color: "800080" #purple
car9:
    name: "car9"
    color: "800080" #purple
car10:
    name: "car10"
    color: "800080" #purple
car11:
    name: "car11"
    color: "800080" #purple
car12:
    name: "car12"
    color: "800080" #purple
car13:
    name: "car13"
    color: "800080" #purple
car14:
    name: "car14"
    color: "800080" #purple
